name: 🤖 Auto label
on: pull_request_review

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: taiga-family/ci/actions/setup/variables@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
      - uses: taiga-family/ci/actions/auto/label-when-approved@e9c5cd341c28d9aeb357b757df41cddcbb674b2d # v1.222.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
